import '../style/globals.css'
import { Inter, Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Hotel Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`relative ${roboto.className}`}>
        {children}
      </body>
    </html>
  )
}
